import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Module 1: Laplace Transforms',
      items: [{type: 'autogenerated', dirName: 'module-1-laplace-transforms'}],
    },
    // {
    //   type: 'category',
    //   label: 'Module 2: Fourier Series',
    //   items: [], // Add markdown files for Module 2 here
    // },
    // {
    //   type: 'category',
    //   label: 'Module 3: Z-Transforms',
    //   items: [], // Add markdown files for Module 3 here
    // },
  ],
};

export default sidebars;
